/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.GIAMGIABUS;
import BUS.NHANVIENBUS;
import BUS.SANPHAMBUS;
import DTO.GIAMGIADTO;
import DTO.SANPHAMDTO;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Admin
 */
public class GIAMGIA extends javax.swing.JFrame {

    /**
     * Creates new form GIAMGIA
     */
    public GIAMGIA() {
        initComponents();
         GIAMGIABUS bus=new GIAMGIABUS();            
            if(bus.dsgg!=null)
                bus.hienthi();
           
            Vector header=new Vector();
                header.add("Mã sản phầm");
                header.add("Mã giảm giá");
                header.add("Phần trăm");
                header.add("Ngày bắt đầu");
                header.add("Ngày kết thúc");
            tbm = new DefaultTableModel(header,0);
            for(int i=0;i<bus.dsgg.size();i++)
            {
                GIAMGIADTO gg=GIAMGIABUS.dsgg.get(i);
                Vector v=new Vector();
                v.add(gg.getMASP());
                v.add(gg.getMAGG());
                v.add(gg.getPHANTRAM());
                v.add(gg.getNGBD());
                v.add(gg.getNGKT());
                tbm.addRow(v);
               
            } jTable2.setModel(tbm);
            
           DefaultComboBoxModel cb=new DefaultComboBoxModel();
           SANPHAMBUS spbus=new SANPHAMBUS();
           spbus.DocSanPham();
           for(SANPHAMDTO sp:SANPHAMBUS.lssanpham){
               cb.addElement(sp.getMASP());
           }
           jComboBoxmasp.setModel(cb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonthem = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonthoat = new javax.swing.JButton();
        jButtondic = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldphantram = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldngbd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldngkt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldmagg = new javax.swing.JTextField();
        jComboBoxmasp = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButtontim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));

        jButtonthem.setText("thêm");
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });

        jButtonsua.setText("sửa");
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });

        jButtonxoa.setText("xóa");
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });

        jButtonthoat.setText("thoát");
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });

        jButtondic.setText("đọc");
        jButtondic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtondic, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthem)
                    .addComponent(jButtondic)
                    .addComponent(jButtonsua)
                    .addComponent(jButtonxoa))
                .addGap(18, 18, 18)
                .addComponent(jButtonthoat)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Mã sản phẩm");

        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Phần trăm");

        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Ngày bắt đầu");

        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Mã giảm giá");

        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Ngày kết thúc");

        jComboBoxmasp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chon ma tai day", "Item 2", "Item 3", "Item 4" }));
        jComboBoxmasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmaspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldngkt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldngbd, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldphantram)
                            .addComponent(jTextFieldmagg)
                            .addComponent(jComboBoxmasp, 0, 187, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmagg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldphantram, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldngbd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldngkt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setForeground(new java.awt.Color(102, 0, 102));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Mã giảm giá", "Phầm trăm", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tìm kiếm nâng cao");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã SP");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mã GG");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButtontim.setText("TÌM");
        jButtontim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jButtontim, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtontim, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jComboBoxmaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmaspActionPerformed

    private void jButtondicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondicActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
           
            GIAMGIABUS bus=new GIAMGIABUS();            
            if(bus.dsgg!=null)
                bus.hienthi();
           
            Vector header=new Vector();
                header.add("Mã sản phầm");
                header.add("Mã giảm giá");
                header.add("Phần trăm");
                header.add("Ngày bắt đầu");
                header.add("Ngày kết thúc");
            tbm =new DefaultTableModel(header,0);
            for(int i=0;i<bus.dsgg.size();i++)
            {
                GIAMGIADTO gg=GIAMGIABUS.dsgg.get(i);
                Vector v=new Vector();
                v.add(gg.getMASP());
                v.add(gg.getMAGG());
                v.add(gg.getPHANTRAM());
                v.add(gg.getNGBD());
                v.add(gg.getNGKT());
                tbm.addRow(v);
               
            } jTable2.setModel(tbm);
            
        } catch (Exception ex) {
            System.out.println("lỗi hiển thị");
        }        
    }//GEN-LAST:event_jButtondicActionPerformed

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed
        // TODO add your handling code here:
        GIAMGIABUS ggbus=new GIAMGIABUS();
        GIAMGIADTO ggdto=new GIAMGIADTO();               
        ggdto.setMASP(jComboBoxmasp.getSelectedItem().toString());
        ggdto.setMAGG(jTextFieldmagg.getText());
        ggdto.setPHANTRAM(jTextFieldphantram.getText());
        ggdto.setNGBD(jTextFieldngbd.getText());
        ggdto.setNGKT(jTextFieldngkt.getText());
        
        try {
            if(ggbus.them(ggdto)==true)
            {
                Vector header=new Vector();
                header.add("Mã sản phầm");
                header.add("Mã giảm giá");
                header.add("Phần trăm");
                header.add("Ngày bắt đầu");
                header.add("Ngày kết thúc");
            tbm =new DefaultTableModel(header,0);
            for(int i=0;i<ggbus.dsgg.size();i++)
            {
                GIAMGIADTO gg=GIAMGIABUS.dsgg.get(i);
                Vector v=new Vector();
                v.add(gg.getMASP());
                v.add(gg.getMAGG());
                v.add(gg.getPHANTRAM());
                v.add(gg.getNGBD());
                v.add(gg.getNGKT());
                tbm.addRow(v);
               
            } jTable2.setModel(tbm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GIAMGIA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        try {
            // TODO add your handling code here:
            GIAMGIADTO ggdto=new GIAMGIADTO();
            ggdto.setMASP(jComboBoxmasp.getSelectedItem().toString());
            ggdto.setMAGG(jTextFieldmagg.getText());
            ggdto.setPHANTRAM(jTextFieldphantram.getText());
            ggdto.setNGBD(jTextFieldngbd.getText());
            ggdto.setNGKT(jTextFieldngkt.getText());
            GIAMGIABUS ggbus=new GIAMGIABUS();
            
            if(ggbus.sua(ggdto)==false)
            {                
                JOptionPane.showMessageDialog(null,"Sửa thất bại");
                return;           
            }
            
            JOptionPane.showMessageDialog(null,"Sửa thành công");
            int i=jTable2.getSelectedRow();
            tbm.setValueAt(jComboBoxmasp.getSelectedItem().toString(),i,0);
            tbm.setValueAt(jTextFieldmagg.getText(), i,1);
            tbm.setValueAt(jTextFieldphantram.getText(), i,2);
            tbm.setValueAt(jTextFieldngbd.getText(), i,3);
            tbm.setValueAt(jTextFieldngkt.getText(), i,4);
            jTable2.setModel(tbm);
        } catch (SQLException ex) {
            Logger.getLogger(GIAMGIA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i=jTable2.getSelectedRow();
         if(i>=0){
             jComboBoxmasp.setSelectedItem(jTable2.getValueAt(i,0).toString());
             jTextFieldmagg.setText(jTable2.getValueAt(i,1).toString());
             jTextFieldphantram.setText(jTable2.getValueAt(i,2).toString());
             jTextFieldngbd.setText(jTable2.getValueAt(i,3).toString());
             jTextFieldngkt.setText(jTable2.getValueAt(i,4).toString());
         }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here:
        int i=jTable2.getSelectedRow();
        if(i>=0 ){           
            {
                try {
                    GIAMGIABUS bus=new GIAMGIABUS();
                    if(GIAMGIABUS.dsgg==null)
                        bus.hienthi();
                    
                    GIAMGIADTO a=new GIAMGIADTO();
                    a.setMASP(jComboBoxmasp.getSelectedItem().toString());
                    a.setMAGG(jTextFieldmagg.getText());
                    a.setPHANTRAM(jTextFieldphantram.getText());
                    a.setNGBD(jTextFieldngbd.getText());               
                    a.setNGKT(jTextFieldngkt.getText());   
                    System.out.println(a.getMAGG());
                    if(bus.xoa(a)==false)
                        System.out.println("Không thể xóa");                    
                    bus.xoa2(a);
                    //model.removeRow(i);
                    //jTable1.setModel(model);
        
                    Vector header=new Vector();
                    header.add("Mã sản phầm");
                    header.add("Mã giảm giá");
                    header.add("Phần trăm");
                    header.add("Ngày bắt đầu");
                    header.add("Ngày kết thúc");
                  
                    DefaultTableModel model = new DefaultTableModel(header,0);

                    for(GIAMGIADTO gg:GIAMGIABUS.dsgg){
                        Vector r=new Vector();
                        r.add(gg.getMASP());
                        r.add(gg.getMAGG());
                        r.add(gg.getPHANTRAM());
                        r.add(gg.getNGBD());
                        r.add(gg.getNGKT());                        
                        model.addRow(r);
                    }
                    jTable2.setModel(model);

                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtontimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimActionPerformed
        // TODO add your handling code here:
        String MASP=jTextField1.getText();
        String MAGG=jTextField2.getText();              
              Vector header=new Vector();
                header.add("Mã sản phầm");
                header.add("Mã giảm giá");
                header.add("Phần trăm");
                header.add("Ngày bắt đầu");
                header.add("Ngày kết thúc");
        tbm= new DefaultTableModel(header,0);
        GIAMGIABUS ggb=new GIAMGIABUS();
        ArrayList<GIAMGIADTO> ggtk=ggb.tknc(MASP,MAGG);
        for(GIAMGIADTO gg:ggtk){
            Vector a=new Vector();
            a.add(gg.getMASP());
            a.add(gg.getMAGG());
            a.add(gg.getPHANTRAM());
            a.add(gg.getNGBD());
            a.add(gg.getNGKT());
            tbm.addRow(a);
        }
        jTable2.setModel(tbm);
    }//GEN-LAST:event_jButtontimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIAMGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIAMGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIAMGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIAMGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIAMGIA().setVisible(true);
            }
        });
    }
    private DefaultTableModel tbm = new DefaultTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondic;
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtontim;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JComboBox<String> jComboBoxmasp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldmagg;
    private javax.swing.JTextField jTextFieldngbd;
    private javax.swing.JTextField jTextFieldngkt;
    private javax.swing.JTextField jTextFieldphantram;
    // End of variables declaration//GEN-END:variables
}
