/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.plaf.metal.MetalBorders;

/**
 *
 * @author Admin
 */
public class GIAODIENCHINH extends javax.swing.JFrame {

    /**
     * Creates new form GIAODIENCHINH
     */
    public GIAODIENCHINH() {
        initComponents();
        thaydoimauchu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelquan = new javax.swing.JLabel();
        jLabeldung = new javax.swing.JLabel();
        jLabelli = new javax.swing.JLabel();
        jLabelao = new javax.swing.JLabel();
        jLabelcua = new javax.swing.JLabel();
        jLabelhang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonGIAMGIA = new javax.swing.JButton();
        jButtonHOADON = new javax.swing.JButton();
        jButtonKHACHHANG = new javax.swing.JButton();
        jButtonLOAISANPHAM = new javax.swing.JButton();
        jButtonNHACUNGCUNGCAP = new javax.swing.JButton();
        jButtonPHIEUNHAPHANG = new javax.swing.JButton();
        jButtonSANPHAM = new javax.swing.JButton();
        jButtonTHOAT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelquan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelquan.setText("QUẢN LÍ CỬA");

        jLabeldung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabelli.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelli.setText("HÀNG");

        jLabelao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelao.setText("KHOÁC");

        jLabelcua.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelcua.setText("BÁN");

        jLabelhang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelhang.setText("ÁO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabeldung)
                .addGap(44, 44, 44)
                .addComponent(jLabelquan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelcua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelao)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeldung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelquan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelcua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonGIAMGIA.setText("QUẢN LÍ GIẢM GIÁ");
        jButtonGIAMGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGIAMGIAActionPerformed(evt);
            }
        });

        jButtonHOADON.setText("QUẢN LÍ HÓA ĐƠN");
        jButtonHOADON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHOADONActionPerformed(evt);
            }
        });

        jButtonKHACHHANG.setText("QUẢN LÍ KHÁCH HÀNG");
        jButtonKHACHHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKHACHHANGActionPerformed(evt);
            }
        });

        jButtonLOAISANPHAM.setText("QUẢN LÍ LOẠI SẢN PHẨM");
        jButtonLOAISANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOAISANPHAMActionPerformed(evt);
            }
        });

        jButtonNHACUNGCUNGCAP.setText("QUẢN LÍ NHÀ CUNG CẤP");
        jButtonNHACUNGCUNGCAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNHACUNGCUNGCAPActionPerformed(evt);
            }
        });

        jButtonPHIEUNHAPHANG.setText("QUẢN LÍ PHIẾU NHẬP HÀNG");
        jButtonPHIEUNHAPHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPHIEUNHAPHANGActionPerformed(evt);
            }
        });

        jButtonSANPHAM.setText("QUẢN LÍ SẢN PHẨM");
        jButtonSANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSANPHAMActionPerformed(evt);
            }
        });

        jButtonTHOAT.setForeground(new java.awt.Color(255, 0, 0));
        jButtonTHOAT.setText("ĐÓNG ỨNG DỤNG");
        jButtonTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTHOATActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPHIEUNHAPHANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLOAISANPHAM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSANPHAM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonHOADON, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonKHACHHANG, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonNHACUNGCUNGCAP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGIAMGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTHOAT, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHOADON, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKHACHHANG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSANPHAM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLOAISANPHAM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNHACUNGCUNGCAP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGIAMGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPHIEUNHAPHANG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTHOAT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGIAMGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGIAMGIAActionPerformed
        // TODO add your handling code here:
        GIAMGIA giamgia=new GIAMGIA();
        giamgia.setVisible(true);
    }//GEN-LAST:event_jButtonGIAMGIAActionPerformed

    private void jButtonHOADONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHOADONActionPerformed
        // TODO add your handling code here:
        Hoadon hd=new Hoadon();
        hd.setVisible(true);
    }//GEN-LAST:event_jButtonHOADONActionPerformed

    private void jButtonKHACHHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKHACHHANGActionPerformed
        // TODO add your handling code here:
        KHACHHANG kh=new KHACHHANG();
        kh.setVisible(true);
    }//GEN-LAST:event_jButtonKHACHHANGActionPerformed

    private void jButtonLOAISANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOAISANPHAMActionPerformed
        // TODO add your handling code here:
        LoaiSanPhamGUI lsp=new LoaiSanPhamGUI();
        lsp.setVisible(true);
    }//GEN-LAST:event_jButtonLOAISANPHAMActionPerformed

    private void jButtonNHACUNGCUNGCAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNHACUNGCUNGCAPActionPerformed
        // TODO add your handling code here:
        NCC n=new NCC();
        n.setVisible(true);
    }//GEN-LAST:event_jButtonNHACUNGCUNGCAPActionPerformed

    private void jButtonPHIEUNHAPHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPHIEUNHAPHANGActionPerformed
        // TODO add your handling code here:
        PHIEUNHAPHANG pn=new PHIEUNHAPHANG();
        pn.setVisible(true);
    }//GEN-LAST:event_jButtonPHIEUNHAPHANGActionPerformed

    private void jButtonSANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSANPHAMActionPerformed
        // TODO add your handling code here:
        Sanpham sp=new Sanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_jButtonSANPHAMActionPerformed

    private void jButtonTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTHOATActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonTHOATActionPerformed

    public void thaydoimauchu(){
        java.util.Timer tm= new Timer();
        tm.schedule(new TimerTask() {
            @Override
            public void run() {
                if(mau==0){
                  
                                     
                    jLabeldung.setForeground(Color.BLUE);
                }
                else if(mau==1){
                    jLabeldung.setForeground(Color.red);
                   
                    jLabelquan.setForeground(Color.blue);
                }
                else if(mau==2){
                    jLabelquan.setForeground(Color.red);
                    jLabeldung.setForeground(Color.BLACK);
                    jLabelli.setForeground(Color.blue);
                }
                else if(mau==3){
                    jLabelli.setForeground(Color.red);
                    jLabelquan.setForeground(Color.BLACK);
                    jLabelcua.setForeground(Color.blue);
                }
                else if(mau==4){
                    jLabelcua.setForeground(Color.red);
                    jLabelli.setForeground(Color.BLACK);
                    jLabelhang.setForeground(Color.blue);
                }
                else if(mau==5){
                    jLabelhang.setForeground(Color.red);
                    jLabelcua.setForeground(Color.BLACK);
                    jLabelao.setForeground(Color.blue);
                }
                else if(mau==6){
                    jLabelao.setForeground(Color.red);
                    jLabelhang.setForeground(Color.BLACK);
                   
                }
                else if(mau==7){
                    
                    jLabelao.setForeground(Color.BLACK);
                    
                }
                ++mau;
                if(mau>7)
                    mau=0;
            }
        },0,300);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIAODIENCHINH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GIAODIENCHINH().setVisible(true);
            }
        });
    }
    private int mau=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGIAMGIA;
    private javax.swing.JButton jButtonHOADON;
    private javax.swing.JButton jButtonKHACHHANG;
    private javax.swing.JButton jButtonLOAISANPHAM;
    private javax.swing.JButton jButtonNHACUNGCUNGCAP;
    private javax.swing.JButton jButtonPHIEUNHAPHANG;
    private javax.swing.JButton jButtonSANPHAM;
    private javax.swing.JButton jButtonTHOAT;
    private javax.swing.JLabel jLabelao;
    private javax.swing.JLabel jLabelcua;
    private javax.swing.JLabel jLabeldung;
    private javax.swing.JLabel jLabelhang;
    private javax.swing.JLabel jLabelli;
    private javax.swing.JLabel jLabelquan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
