/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.Connect;
import BUS.CHITIETHOADONBUS;
import BUS.GIAMGIABUS;
import BUS.HOADONBUS;
import BUS.KHACHHANGBUS;
import BUS.NHANVIENBUS;
import BUS.SANPHAMBUS;
import DTO.CHITIETHOADONDTO;
import DTO.GIAMGIADTO;
import DTO.HOADONDTO;
import DTO.KHACHHANGDTO;
import DTO.NHANVIENDTO;
import DTO.SANPHAMDTO;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Hoadon extends javax.swing.JFrame {


    public Hoadon() {
        initComponents();
        KHACHHANGBUS khbus=new KHACHHANGBUS();
        khbus.doc();
        DefaultComboBoxModel mdcbkh=new DefaultComboBoxModel();
        for(KHACHHANGDTO kh : KHACHHANGBUS.dskhbus)
            mdcbkh.addElement(kh.getMAKH());
        
        jComboBoxMAKH.setModel(mdcbkh);
        
        SANPHAMBUS spbus=new SANPHAMBUS();
        spbus.DocSanPham();
        
        loadmasp();
        
        
       
        
        NHANVIENBUS nvbus=new NHANVIENBUS();
        nvbus.hienthi();
        
        DefaultComboBoxModel mdcbnv=new DefaultComboBoxModel();
        for(NHANVIENDTO nvdto : NHANVIENBUS.dsnv)
            mdcbnv.addElement(nvdto.getMANV());
        
        jComboBoxMANV.setModel(mdcbnv);
        loadhoadon();
        jTextFieldsoluongcthd.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }
            public void capnhatthanhtien(){
              
                double tt=0.0;
                try{
                    double soluong=Double.parseDouble(jTextFieldsoluongcthd.getText());
                    double dongia=Double.parseDouble(jTextFielddongiacthd.getText());
                    double giamgia=Double.parseDouble(jTextFieldgiamgiacthd.getText());
                    tt=soluong*(dongia-giamgia);
                    
                }
                catch(NumberFormatException e){
                    return;
                }
                jTextFieldthanhtiencthd.setText(String.valueOf(tt));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablehoadon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtondoc = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtonthem = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonthoat = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldgiamin = new javax.swing.JTextField();
        jTextFieldgiamax = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldtongtien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldngaygd = new javax.swing.JTextField();
        jComboBoxMANV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMAKH = new javax.swing.JComboBox<>();
        jTextFieldmahd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablechitiethoadon = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtontimtheoma = new javax.swing.JButton();
        jButtonsuachitiet = new javax.swing.JButton();
        jButtonxoachitiet = new javax.swing.JButton();
        jButtonthemchitiet = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldmahdcthd = new javax.swing.JTextField();
        jTextFieldsoluongcthd = new javax.swing.JTextField();
        jTextFielddongiacthd = new javax.swing.JTextField();
        jTextFieldgiamgiacthd = new javax.swing.JTextField();
        jTextFieldthanhtiencthd = new javax.swing.JTextField();
        jComboBoxmaspcthd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hóa Đơn");

        jTablehoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTablehoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablehoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablehoadon);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtondoc.setText("Đọc");
        jButtondoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondocActionPerformed(evt);
            }
        });

        jButtonsua.setText("Sửa");
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });

        jButtonthem.setText("Thêm");
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });

        jButtonxoa.setText("Xóa");
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });

        jButtonthoat.setText("Thoát");
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Chức năng");

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Khoảng tổng tiền HD");

        jLabel22.setText("Từ");

        jLabel23.setText("Đến");

        jTextFieldgiamin.setText("0");

        jTextFieldgiamax.setText("2000000000");
        jTextFieldgiamax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgiamaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldgiamax, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldgiamin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldgiamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldgiamax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(20, 20, 20))
        );

        jButton3.setText("Tìm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tìm nâng cao");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton3)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonthoat, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jButtonthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtondoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonsua)
                    .addComponent(jButtondoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonxoa)
                    .addComponent(jButtonthem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonthoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(204, 255, 204));

        jTextFieldtongtien.setEditable(false);

        jLabel7.setText("Tổng tiền");

        jLabel6.setText("Ngày Giao dịch");

        jTextFieldngaygd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldngaygdActionPerformed(evt);
            }
        });

        jComboBoxMANV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMANV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMANVActionPerformed(evt);
            }
        });

        jLabel5.setText("MÃ Nhân viên");

        jLabel4.setText("MÃ Khách hàng");

        jLabel3.setText("MÃ hóa đơn");

        jComboBoxMAKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldmahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmahdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Thông tin hóa đơn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldmahd)
                    .addComponent(jComboBoxMAKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldngaygd)
                    .addComponent(jComboBoxMANV, 0, 115, Short.MAX_VALUE)
                    .addComponent(jTextFieldtongtien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldngaygd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldtongtien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 420, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chi tiết hóa đơn");

        jTablechitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Đơn Giá", "Số Lượng ", "Giảm Giá", "Thành Tiền"
            }
        ));
        jTablechitiethoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablechitiethoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablechitiethoadon);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jPanel5VetoableChange(evt);
            }
        });

        jButtontimtheoma.setText("Tìm theo mã SP");

        jButtonsuachitiet.setText("Sửa chi tiết");
        jButtonsuachitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuachitietActionPerformed(evt);
            }
        });

        jButtonxoachitiet.setText("Xóa chi tiết");
        jButtonxoachitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoachitietActionPerformed(evt);
            }
        });

        jButtonthemchitiet.setText("Thêm chi tiết");
        jButtonthemchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemchitietActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã HD");

        jLabel10.setText("Mã SP");

        jLabel11.setText("Số lượng");

        jLabel12.setText("Đơn giá");

        jLabel13.setText("Thành tiền");

        jLabel14.setText("Giảm đơn giá");

        jTextFieldmahdcthd.setEditable(false);
        jTextFieldmahdcthd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldmahdcthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmahdcthdActionPerformed(evt);
            }
        });

        jTextFieldsoluongcthd.setText("0");

        jTextFielddongiacthd.setEditable(false);
        jTextFielddongiacthd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFielddongiacthd.setForeground(new java.awt.Color(255, 0, 51));

        jTextFieldgiamgiacthd.setEditable(false);

        jTextFieldthanhtiencthd.setEditable(false);
        jTextFieldthanhtiencthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldthanhtiencthdActionPerformed(evt);
            }
        });

        jComboBoxmaspcthd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxmaspcthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmaspcthdActionPerformed(evt);
            }
        });

        jLabel15.setText("VND");

        jLabel16.setText("VND");

        jLabel17.setText("VND");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Chức Năng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldmahdcthd)
                            .addComponent(jTextFieldsoluongcthd)
                            .addComponent(jComboBoxmaspcthd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonthemchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonxoachitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonsuachitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontimtheoma))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldgiamgiacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldthanhtiencthd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFielddongiacthd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthemchitiet)
                    .addComponent(jButtonxoachitiet)
                    .addComponent(jButtonsuachitiet)
                    .addComponent(jButtontimtheoma))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmahdcthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddongiacthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgiamgiacthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmaspcthd)
                    .addComponent(jLabel16))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsoluongcthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldthanhtiencthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        // TODO add your handling code here:
        HOADONDTO dto=new HOADONDTO();
        dto.setMAHD(jTextFieldmahd.getText());
        dto.setMAKH(jComboBoxMAKH.getSelectedItem().toString());
        dto.setMANV(jComboBoxMANV.getSelectedItem().toString());
        dto.setNGAYGD(jTextFieldngaygd.getText());
        dto.setTONGTIEN(jTextFieldtongtien.getText());
        HOADONBUS bus=new HOADONBUS();
        try {
            if(bus.sua(dto)==true)
            {
                Vector a= new Vector();
                a.add("Mã Hóa Đơn");
                a.add("Mã Kh.Hàng");
                a.add("Mã Nh.Viên");
                a.add("Ngày G.Dịch");
                a.add("Tổng tiền");
                DefaultTableModel model = new DefaultTableModel(a,0);
                for(HOADONDTO dto1: HOADONBUS.dshd){
                    Vector r=new Vector();
                    r.add(dto1.getMAHD());
                    r.add(dto1.getMAKH());
                    r.add(dto1.getMANV());
                    r.add(dto1.getNGAYGD());
                    r.add(dto1.getTONGTIEN());
                    model.addRow(r);
                }
                jTablehoadon.setModel(model);

            }
        } catch (Exception ex) {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jTextFieldmahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmahdActionPerformed

    private void jComboBoxMANVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMANVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMANVActionPerformed

    private void jButtondocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondocActionPerformed
        // TODO add your handling code here:
        HOADONBUS bus= new HOADONBUS();
        bus.doc();
        Vector a= new Vector();
        a.add("Mã Hóa Đơn");
        a.add("Mã Kh.Hàng");
        a.add("Mã Nh.Viên");
        a.add("Ngày G.Dịch");
        a.add("Tổng tiền");
        DefaultTableModel model = new DefaultTableModel(a,0);
        for(HOADONDTO dto: HOADONBUS.dshd){
            Vector r=new Vector();
            r.add(dto.getMAHD());
            r.add(dto.getMAKH());
            r.add(dto.getMANV());
            r.add(dto.getNGAYGD());
            r.add(dto.getTONGTIEN());
            model.addRow(r);
        }
        jTablehoadon.setModel(model);
        dangthongke=0;
        
    }//GEN-LAST:event_jButtondocActionPerformed

    private void jTablehoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablehoadonMouseClicked
        // TODO add your handling code here:
        if(dangthongke!=0)
            return;
        int i=jTablehoadon.getSelectedRow();
        if(i>=0){
            loadmasp();
            jTextFieldmahd.setText(jTablehoadon.getValueAt(i, 0).toString());
            jComboBoxMAKH.setSelectedItem(jTablehoadon.getValueAt(i, 1).toString());
            jComboBoxMANV.setSelectedItem(jTablehoadon.getValueAt(i, 2).toString());
            jTextFieldngaygd.setText(jTablehoadon.getValueAt(i, 3).toString());
            try{
                jTextFieldtongtien.setText(jTablehoadon.getValueAt(i, 4).toString());
            }
            catch( Exception e){
                jTextFieldtongtien.setText("");
            }
            jTextFieldmahdcthd.setText(jTextFieldmahd.getText());
            
            loadcthd();
            
        }
    }//GEN-LAST:event_jTablehoadonMouseClicked

    public void loadcthd(){
        Vector hect=new Vector();
            hect.add("Mã Hóa Đơn");
            hect.add("Mã Sản Phẩm");
            hect.add("Đơn Giá");
            hect.add("Số Lượng");
            hect.add("Giảm Giá");
            hect.add("Thành Tiền");
            DefaultTableModel mdcthd=new DefaultTableModel(hect,0);
            CHITIETHOADONBUS ctbus=new CHITIETHOADONBUS();
            
            ctbus.doc();
            for(CHITIETHOADONDTO cthddto : CHITIETHOADONBUS.dscthd)
            {
                if(cthddto.getMAHD().equals(jTextFieldmahd.getText()))
                {
                    Vector h=new Vector();
                    h.add(cthddto.getMAHD());
                    h.add(cthddto.getMASP());
                    h.add(cthddto.getDONGIA());
                    h.add(cthddto.getSOLUONG());
                    h.add(cthddto.getGIAMGIA());
                    h.add(cthddto.getTHANHTIEN());
                    mdcthd.addRow(h);
                }
            }
            jTablechitiethoadon.setModel(mdcthd);
    }
    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed
        try {
            // TODO add your handling code here:
            dangthongke=0;
            jTextFieldtongtien.setText("0");
            HOADONBUS bus= new HOADONBUS();
            HOADONDTO dto= new HOADONDTO();
            dto.setMAHD(jTextFieldmahd.getText());
            dto.setMAKH(jComboBoxMAKH.getSelectedItem().toString());
            dto.setMANV(jComboBoxMANV.getSelectedItem().toString());
            dto.setNGAYGD(jTextFieldngaygd.getText());
            dto.setTONGTIEN(jTextFieldtongtien.getText());
            if(bus.them(dto)==false)
                return;
            
            Vector a= new Vector();
            a.add("Mã Hóa Đơn");
            a.add("Mã Kh.Hàng");
            a.add("Mã Nh.Viên");
            a.add("Ngày G.Dịch");
            a.add("Tổng tiền");
            DefaultTableModel model = new DefaultTableModel(a,0);
            for(HOADONDTO dto1: HOADONBUS.dshd){
                Vector r=new Vector();
                r.add(dto1.getMAHD());
                r.add(dto1.getMAKH());
                r.add(dto1.getMANV());
                r.add(dto1.getNGAYGD());
                r.add(dto1.getTONGTIEN());
                model.addRow(r);
            }
            jTablehoadon.setModel(model);
            
        } catch (Exception ex) {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here:
        int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
        if(xoa!=0)
            return;
        dangthongke=0;
        int i=jTablehoadon.getSelectedRow();
        if(i>=0){
            try {
                HOADONBUS bus=new HOADONBUS();
                if(HOADONBUS.dshd==null)
                {
                    bus.doc();
                }
                HOADONDTO a=new HOADONDTO();
                a.setMAHD(jTablehoadon.getValueAt(i, 0).toString());
                a.setMAKH(jTablehoadon.getValueAt(i, 1).toString());
                a.setMANV(jTablehoadon.getValueAt(i, 2).toString());
                
                if(bus.Xoa(a)==false)
                    return;
                bus.xoavitrids(i);
                
                Vector a1= new Vector();
                a1.add("Mã Hóa Đơn");
                a1.add("Mã Kh.Hàng");
                a1.add("Mã Nh.Viên");
                a1.add("Ngày G.Dịch");
                a1.add("Tổng tiền");
                DefaultTableModel model = new DefaultTableModel(a1,0);
                for(HOADONDTO dto1: HOADONBUS.dshd){
                    Vector r=new Vector();
                    r.add(dto1.getMAHD());
                    r.add(dto1.getMAKH());
                    r.add(dto1.getMANV());
                    r.add(dto1.getNGAYGD());
                    r.add(dto1.getTONGTIEN());
                    model.addRow(r);
                }
                jTablehoadon.setModel(model);    
                
                
            } catch (Exception ex) {
                Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Vui lòng click chuột vào bảng bên cạnh để chọn hóa đơn cần xóa");
        }
        
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jTextFieldthanhtiencthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldthanhtiencthdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldthanhtiencthdActionPerformed

    private void jTextFieldmahdcthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmahdcthdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmahdcthdActionPerformed

    private void jButtonthemchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemchitietActionPerformed
        try {
            // TODO add your handling code here:
            
            if(jTextFieldmahdcthd.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn cần thêm tại bảng bên");
                return;
            }
            
            CHITIETHOADONBUS bus=new CHITIETHOADONBUS();
            CHITIETHOADONDTO dto=new CHITIETHOADONDTO();
            dto.setMAHD(jTextFieldmahdcthd.getText());
            dto.setMASP(jComboBoxmaspcthd.getSelectedItem().toString());
            dto.setDONGIA(jTextFielddongiacthd.getText());
            dto.setSOLUONG(jTextFieldsoluongcthd.getText());
            dto.setGIAMGIA(jTextFieldgiamgiacthd.getText());
            dto.setTHANHTIEN(jTextFieldthanhtiencthd.getText());
            
            if(bus.them(dto)==true){
                loadhoadon();
                loadcthd();
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonthemchitietActionPerformed

    private void jComboBoxmaspcthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmaspcthdActionPerformed
         // TODO add your handling code here:
        try{
            Date.valueOf(jTextFieldngaygd.getText().toString());
        }
        catch(Exception e){
            return;
        }
        for(SANPHAMDTO sp: SANPHAMBUS.lssanpham){
            if(sp.getMASP().equals(jComboBoxmaspcthd.getSelectedItem().toString()))
            {
                int ktgg=0;
                jTextFielddongiacthd.setText(sp.getDONGIA());
                GIAMGIABUS ggbus=new GIAMGIABUS();
                double dongia=Double.parseDouble(sp.getDONGIA());
                double ptgg=0;
                ggbus.hienthi();
                for(GIAMGIADTO ggdto: GIAMGIABUS.dsgg)
                {
                    
                    if(ggdto.getMASP().equals(sp.getMASP()) ){
                        
                        Date date1=Date.valueOf(ggdto.getNGBD());
                        Date date2=Date.valueOf(ggdto.getNGKT());
                        Date date3=Date.valueOf(jTextFieldngaygd.getText());
                        if(date3.compareTo(date1)>=0 && date3.compareTo(date2)<=0)
                        {
                            ptgg=Double.parseDouble(ggdto.getPHANTRAM());
                            ktgg=1;
                            jTextFieldgiamgiacthd.setText( String.valueOf(dongia*ptgg/100)  );
                        }
                    }
                }
                if(ktgg==0)
                    jTextFieldgiamgiacthd.setText("0");
                if(!jTextFieldsoluongcthd.getText().equals(""))
                {
                    try{
                        Integer.parseInt(jTextFieldsoluongcthd.getText());
                    }
                    catch (NumberFormatException e){
                        return;
                    }
                    double sl=Double.parseDouble(jTextFieldsoluongcthd.getText());
                    double tt=sl*(dongia-dongia*ptgg/100);
                    jTextFieldthanhtiencthd.setText(String.valueOf(tt));
                }
                break;
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jComboBoxmaspcthdActionPerformed

    private void jPanel5VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jPanel5VetoableChange

    }//GEN-LAST:event_jPanel5VetoableChange

    private void jButtonxoachitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoachitietActionPerformed
        // TODO add your handling code here:
        
        int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
        if(xoa!=0)
            return;
        
        int i=jTablechitiethoadon.getSelectedRow();
        if(i>=0){
            try {
                CHITIETHOADONDTO cthddto=new CHITIETHOADONDTO();
                cthddto.setMASP(jComboBoxmaspcthd.getSelectedItem().toString());
                cthddto.setMAHD(jTextFieldmahd.getText());
                CHITIETHOADONBUS bus=new CHITIETHOADONBUS();
                if(bus.Xoa(cthddto)==true){
                    for(int j=0;j<bus.dscthd.size();++j){
                        if(bus.dscthd.get(j).getMAHD().equals(cthddto.getMAHD()) && bus.dscthd.get(j).getMASP().equals(cthddto.getMASP()))
                            bus.xoavitrids(j);
                        }
                loadcthd();
                loadhoadon();
                }else{
                    JOptionPane.showConfirmDialog(null,"Xóa thất bại !!");
                }
            } catch (Exception ex) {
                Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonxoachitietActionPerformed

    private void jTablechitiethoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablechitiethoadonMouseClicked
        // TODO add your handling code here:
        int i=jTablechitiethoadon.getSelectedRow();
        if(i>=0){
            if(jTextFieldmahdcthd.getText().equals(""))
                return;
            jTextFielddongiacthd.setText(jTablechitiethoadon.getValueAt(i,2).toString());
            jTextFieldsoluongcthd.setText(jTablechitiethoadon.getValueAt(i,3).toString());
            jTextFieldgiamgiacthd.setText(jTablechitiethoadon.getValueAt(i,4).toString());
            jTextFieldthanhtiencthd.setText(jTablechitiethoadon.getValueAt(i,5).toString());
            jComboBoxmaspcthd.setSelectedItem(jTablechitiethoadon.getValueAt(i,1));
        }
        
    }//GEN-LAST:event_jTablechitiethoadonMouseClicked

    private void jButtonsuachitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuachitietActionPerformed
        try {
            // TODO add your handling code here:
            
            if(jTextFieldmahdcthd.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn cần thêm tại bảng bên");
                return;
            }
            
            CHITIETHOADONBUS bus=new CHITIETHOADONBUS();
            CHITIETHOADONDTO dto=new CHITIETHOADONDTO();
            dto.setMAHD(jTextFieldmahdcthd.getText());
            dto.setMASP(jComboBoxmaspcthd.getSelectedItem().toString());
            dto.setDONGIA(jTextFielddongiacthd.getText());
            dto.setSOLUONG(jTextFieldsoluongcthd.getText());
            dto.setGIAMGIA(jTextFieldgiamgiacthd.getText());
            dto.setTHANHTIEN(jTextFieldthanhtiencthd.getText());
            
            if(bus.sua(dto)==true){
                loadhoadon();
                loadcthd();
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonsuachitietActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HOADONBUS bus=new HOADONBUS();
        
        ArrayList<HOADONDTO> rr=new ArrayList<>();
        rr=bus.timnangcao(jTextFieldgiamin.getText(),jTextFieldgiamax.getText());
        if(rr!=null){
            Vector a= new Vector();
            a.add("Mã Hóa Đơn");
            a.add("Mã Kh.Hàng");
            a.add("Mã Nh.Viên");
            a.add("Ngày G.Dịch");
            a.add("Tổng tiền");
            DefaultTableModel model = new DefaultTableModel(a,0);
            for(HOADONDTO dto: rr){
                Vector r=new Vector();
                r.add(dto.getMAHD());
                r.add(dto.getMAKH());
                r.add(dto.getMANV());
                r.add(dto.getNGAYGD());
                r.add(dto.getTONGTIEN());
                model.addRow(r);
            }
            jTablehoadon.setModel(model);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldgiamaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgiamaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgiamaxActionPerformed

    private void jTextFieldngaygdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldngaygdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldngaygdActionPerformed

    public void loadmasp(){
        DefaultComboBoxModel mdsp=new DefaultComboBoxModel();
        mdsp.addElement("Chọn Mã SP");
        for(SANPHAMDTO sp: SANPHAMBUS.lssanpham)
            mdsp.addElement(sp.getMASP());
        jComboBoxmaspcthd.setModel(mdsp);
    }
    public void  loadhoadon(){
        HOADONBUS bus= new HOADONBUS();
        bus.doc();
        Vector a= new Vector();
        a.add("Mã Hóa Đơn");
        a.add("Mã Kh.Hàng");
        a.add("Mã Nh.Viên");
        a.add("Ngày G.Dịch");
        a.add("Tổng tiền");
        DefaultTableModel model = new DefaultTableModel(a,0);
        for(HOADONDTO dto: HOADONBUS.dshd){
            try {
                Vector r=new Vector();
                r.add(dto.getMAHD());
                r.add(dto.getMAKH());
                r.add(dto.getMANV());
                r.add(dto.getNGAYGD());
                r.add(dto.getTONGTIEN());
                if(dto.getTONGTIEN()==null)
                    dto.setTONGTIEN("0");
                bus.sua2(dto);
                model.addRow(r);
            } catch (Exception ex) {
                Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jTablehoadon.setModel(model);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoadon().setVisible(true);
            }
        });
    }
    
    private int dangthongke=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtondoc;
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonsuachitiet;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthemchitiet;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtontimtheoma;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JButton jButtonxoachitiet;
    private javax.swing.JComboBox<String> jComboBoxMAKH;
    private javax.swing.JComboBox<String> jComboBoxMANV;
    private javax.swing.JComboBox<String> jComboBoxmaspcthd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablechitiethoadon;
    private javax.swing.JTable jTablehoadon;
    private javax.swing.JTextField jTextFielddongiacthd;
    private javax.swing.JTextField jTextFieldgiamax;
    private javax.swing.JTextField jTextFieldgiamgiacthd;
    private javax.swing.JTextField jTextFieldgiamin;
    private javax.swing.JTextField jTextFieldmahd;
    private javax.swing.JTextField jTextFieldmahdcthd;
    private javax.swing.JTextField jTextFieldngaygd;
    private javax.swing.JTextField jTextFieldsoluongcthd;
    private javax.swing.JTextField jTextFieldthanhtiencthd;
    private javax.swing.JTextField jTextFieldtongtien;
    // End of variables declaration//GEN-END:variables
}
