/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KHACHHANGBUS;
import DTO.KHACHHANGDTO;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class KHACHHANG extends javax.swing.JFrame {

    /**
     * Creates new form KHACHHANG
     */
    public KHACHHANG() {
        initComponents();
        KHACHHANGBUS bus=new KHACHHANGBUS();
        if(KHACHHANGBUS.dskhbus==null)
            bus.doc();
        
        Vector he=new Vector();
        he.add("Mã KH");
        he.add("Tên KH");
        he.add("Địa chỉ");
        he.add("SDT");
        model=new DefaultTableModel(he,0);
        
        for(KHACHHANGDTO kh:KHACHHANGBUS.dskhbus){
            Vector r=new Vector();
            r.add(kh.getMAKH());
            r.add(kh.getTENKH());
            r.add(kh.getDIACHI());
            r.add(kh.getSDT());
            model.addRow(r);
        }
        jTable1.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldkhachhang = new javax.swing.JTextField();
        jTextFieldtenkhachhang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFielddiachi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldsodienthoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonthoat = new javax.swing.JButton();
        jButtondcotudb = new javax.swing.JButton();
        jButtonthem = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtontimtheoma = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldtenkhachhangnc = new javax.swing.JTextField();
        jTextFielddiachinc = new javax.swing.JTextField();
        jTextFieldsdtnc = new javax.swing.JTextField();
        jButtontimnc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MAKH", "TENKH", "DIACHI", "SDT"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextFieldkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldkhachhangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Địa chỉ");

        jTextFielddiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddiachiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số điện thoại");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã khách hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên khách hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldtenkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldtenkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFielddiachi, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 3, 3, new java.awt.Color(255, 255, 0)));

        jButtonthoat.setText("Thoát");
        jButtonthoat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 204)));
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });

        jButtondcotudb.setBackground(new java.awt.Color(204, 51, 255));
        jButtondcotudb.setText("Đọc từ database");
        jButtondcotudb.setBorder(new javax.swing.border.MatteBorder(null));
        jButtondcotudb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondcotudbActionPerformed(evt);
            }
        });

        jButtonthem.setBackground(new java.awt.Color(153, 153, 0));
        jButtonthem.setText("Thêm");
        jButtonthem.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });

        jButtonsua.setBackground(new java.awt.Color(0, 102, 102));
        jButtonsua.setText("Sửa");
        jButtonsua.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 153)));
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });

        jButtonxoa.setText("Xóa");
        jButtonxoa.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(102, 51, 255)));
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });

        jButtontimtheoma.setText("Tìm theo mã");
        jButtontimtheoma.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(153, 0, 153)));
        jButtontimtheoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimtheomaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CHỨC NĂNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtontimtheoma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonthoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonxoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonsua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonthem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtondcotudb, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtondcotudb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtontimtheoma, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFielddiachinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddiachincActionPerformed(evt);
            }
        });

        jButtontimnc.setBackground(new java.awt.Color(255, 0, 51));
        jButtontimnc.setText("Tìm kiếm");
        jButtontimnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimncActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tên KH");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Địa chỉ");
        jLabel7.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SDT");
        jLabel8.setPreferredSize(new java.awt.Dimension(41, 16));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tìm nâng cao");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtontimnc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldtenkhachhangnc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(jTextFieldsdtnc, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFielddiachinc, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldtenkhachhangnc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielddiachinc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldsdtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtontimnc)
                .addGap(121, 121, 121))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Thông tin khách hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielddiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddiachiActionPerformed

    private void jButtondcotudbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondcotudbActionPerformed
        // TODO add your handling code here:
        dangdocfile=0;
        dangthongke=0;
        KHACHHANGBUS bus=new KHACHHANGBUS();
        if(KHACHHANGBUS.dskhbus==null)
            bus.doc();
        
        Vector he=new Vector();
        he.add("Mã KH");
        he.add("Tên KH");
        he.add("Địa chỉ");
        he.add("SDT");
        model=new DefaultTableModel(he,0);
        
        for(KHACHHANGDTO kh:KHACHHANGBUS.dskhbus){
            Vector r=new Vector();
            r.add(kh.getMAKH());
            r.add(kh.getTENKH());
            r.add(kh.getDIACHI());
            r.add(kh.getSDT());
            model.addRow(r);
        }
        jTable1.setModel(model);

                
    }//GEN-LAST:event_jButtondcotudbActionPerformed

    
    
    private void jTextFieldkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldkhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldkhachhangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(dangthongke==1)
            return;
        int i=jTable1.getSelectedRow();
        if(i>=0){
            jTextFieldkhachhang.setText( jTable1.getValueAt(i, 0).toString());
            jTextFieldtenkhachhang.setText( jTable1.getValueAt(i, 1).toString());
            jTextFielddiachi.setText( jTable1.getValueAt(i, 2).toString());
            jTextFieldsodienthoai.setText( jTable1.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed

        // TODO add your handling code here:
        KHACHHANGDTO a=new KHACHHANGDTO();
        a.setMAKH(jTextFieldkhachhang.getText());
        a.setTENKH(jTextFieldtenkhachhang.getText());
        a.setDIACHI(jTextFielddiachi.getText());
        a.setSDT(jTextFieldsodienthoai.getText());
        KHACHHANGBUS bus=new KHACHHANGBUS();
        try {
            bus.them(a);
        } catch (SQLException ex) {
            Logger.getLogger(KHACHHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(dangdocfile==1)
            return;
        
        if(KHACHHANGBUS.dskhbus==null)
            bus.doc();
        dangthongke=0;
        Vector he=new Vector();
        he.add("Mã KH");
        he.add("Tên KH");
        he.add("Địa chỉ");
        he.add("SDT");
        model=new DefaultTableModel(he,0);
        
        for(KHACHHANGDTO kh:KHACHHANGBUS.dskhbus){
            Vector r=new Vector();
            r.add(kh.getMAKH());
            r.add(kh.getTENKH());
            r.add(kh.getDIACHI());
            r.add(kh.getSDT());
            model.addRow(r);
        }
        jTable1.setModel(model);
 
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        // TODO add your handling code here:
        KHACHHANGDTO a=new KHACHHANGDTO();
        a.setMAKH(jTextFieldkhachhang.getText());
        a.setTENKH(jTextFieldtenkhachhang.getText());
        a.setDIACHI(jTextFielddiachi.getText());
        a.setSDT(jTextFieldsodienthoai.getText());
        
        KHACHHANGBUS bus=new KHACHHANGBUS();
        try {
            bus.sua(a);
        } catch (SQLException ex) {
            Logger.getLogger(KHACHHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(KHACHHANGBUS.dskhbus==null)
            bus.doc();
        
        Vector he=new Vector();
        he.add("Mã KH");
        he.add("Tên KH");
        he.add("Địa chỉ");
        he.add("SDT");
        model=new DefaultTableModel(he,0);
        dangthongke=0;
        for(KHACHHANGDTO kh:KHACHHANGBUS.dskhbus){
            Vector r=new Vector();
            r.add(kh.getMAKH());
            r.add(kh.getTENKH());
            r.add(kh.getDIACHI());
            r.add(kh.getSDT());
            model.addRow(r);
        }
        jTable1.setModel(model);

    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here:
        int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
        if(xoa!=0)
            return;
        int i=jTable1.getSelectedRow();
        
        if(i>=0){           
            {
                KHACHHANGBUS bus=new KHACHHANGBUS();
                KHACHHANGDTO a=new KHACHHANGDTO();
                a.setMAKH(jTextFieldkhachhang.getText());
                a.setTENKH(jTextFieldtenkhachhang.getText());
                a.setDIACHI(jTextFielddiachi.getText());
                a.setSDT(jTextFieldsodienthoai.getText());
                try {
                    bus.xoa(a);
                } catch (SQLException ex) {
                    Logger.getLogger(KHACHHANG.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                model.removeRow(i);
                jTable1.setModel(model);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Vui lòng click vào bảng bên để chọn khách hàng cần xóa");
        }
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jButtontimtheomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimtheomaActionPerformed
        // TODO add your handling code here:
        String se=JOptionPane.showInputDialog("Mời nhập MAKH");
        KHACHHANGBUS kh=new KHACHHANGBUS();
        KHACHHANGDTO aa=new KHACHHANGDTO();
        aa=kh.timtheoma(se);
        if(aa==null)
            JOptionPane.showMessageDialog(null,"Không tìm thấy");
        else{
            jTextFieldkhachhang.setText(aa.getMAKH());
            jTextFieldtenkhachhang.setText(aa.getTENKH());
            jTextFielddiachi.setText(aa.getDIACHI());
            jTextFieldsodienthoai.setText(aa.getSDT());
        }
    }//GEN-LAST:event_jButtontimtheomaActionPerformed

    private void jTextFielddiachincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddiachincActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddiachincActionPerformed

    private void jButtontimncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimncActionPerformed
        // TODO add your handling code here:
        String tenkh=jTextFieldtenkhachhangnc.getText();
        String diachi=jTextFielddiachinc.getText();
        String sdt=jTextFieldsdtnc.getText();                        
            Vector he=new Vector();
                he.add("Mã KH");
                he.add("Tên KH");
                he.add("Địa chỉ");
                he.add("SDT");
        model=new DefaultTableModel(he,0);
        KHACHHANGBUS khb=new KHACHHANGBUS();
        ArrayList<KHACHHANGDTO> khtk=khb.tknc(tenkh,diachi,sdt);
        for(KHACHHANGDTO kh:khtk){
            Vector a=new Vector();
            a.add(kh.getMAKH());
            a.add(kh.getTENKH());
            a.add(kh.getDIACHI());
            a.add(kh.getSDT());            
            model.addRow(a);
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_jButtontimncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHACHHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHACHHANG().setVisible(true);
     
            }
        });
    }
    private DefaultTableModel model;
    static int dangdocfile=0;
    private int dangthongke=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondcotudb;
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtontimnc;
    private javax.swing.JButton jButtontimtheoma;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielddiachi;
    private javax.swing.JTextField jTextFielddiachinc;
    private javax.swing.JTextField jTextFieldkhachhang;
    private javax.swing.JTextField jTextFieldsdtnc;
    private javax.swing.JTextField jTextFieldsodienthoai;
    private javax.swing.JTextField jTextFieldtenkhachhang;
    private javax.swing.JTextField jTextFieldtenkhachhangnc;
    // End of variables declaration//GEN-END:variables
}
