/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Asus
 */
import BUS.CHITIETPHIEUNHAPHANGBUS;
import BUS.NCCBUS;
import BUS.NHANVIENBUS;
import BUS.PHIEUNHAPHANGBUS;
import BUS.SANPHAMBUS;
import DTO.CHITIETPHIEUNHAPHANGDTO;
import DTO.NCCDTO;
import DTO.NHANVIENDTO;
import DTO.PHIEUNHAPHANGDTO;
import DTO.SANPHAMDTO;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
public class PHIEUNHAPHANG extends javax.swing.JFrame {

    /**
     * Creates new form PHIEUNHAPHANG
     */
    public PHIEUNHAPHANG() {
        initComponents();
        loadcbncc();
        loadcbnv();
        loadpn();
        loadmasp();
        jTextFieldsoluong.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                  capnhatthanhtien();
            }
            public void capnhatthanhtien(){
              
                double tt=0.0;
                try{
                    double soluong=Double.parseDouble(jTextFieldsoluong.getText());
                    double dongia=Double.parseDouble(jTextFielddongia.getText());
                    tt=soluong*dongia;
                    
                }
                catch(NumberFormatException e){
                    return;
                }
                jTextFieldthanhtien.setText(String.valueOf(tt));
            }
        });
        jTextFielddongia.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                capnhatthanhtien();
            }
            public void capnhatthanhtien(){
              
                double tt=0.0;
                try{
                    double soluong=Double.parseDouble(jTextFieldsoluong.getText());
                    double dongia=Double.parseDouble(jTextFielddongia.getText());
                    tt=soluong*dongia;
                    
                }
                catch(NumberFormatException e){
                    return;
                }
                jTextFieldthanhtien.setText(String.valueOf(tt));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMAPNH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldngaynhap = new javax.swing.JTextField();
        jTextFieldtongtien = new javax.swing.JTextField();
        jComboBoxmancc = new javax.swing.JComboBox<>();
        jComboBoxmnv = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jButtondoc = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonthoat = new javax.swing.JButton();
        jButtonthem = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtontim = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablephieunhap = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablechitiet_pn = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButtonthemchitiet = new javax.swing.JButton();
        jButtonxoachitiet = new javax.swing.JButton();
        jButtonsuachitiet = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldmapnh_ctpn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFielddongia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldsoluong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldthanhtien = new javax.swing.JTextField();
        jComboBoxmsp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN PHIẾU NHẬP HÀNG");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã PNH");

        jTextFieldMAPNH.setPreferredSize(new java.awt.Dimension(6, 27));

        jLabel3.setText("Mã NCC");

        jLabel4.setText("Ngày nhập");

        jLabel5.setText("Mã NV");

        jLabel6.setText("Tổng tiền");

        jTextFieldngaynhap.setPreferredSize(new java.awt.Dimension(6, 27));

        jTextFieldtongtien.setEditable(false);
        jTextFieldtongtien.setPreferredSize(new java.awt.Dimension(6, 27));

        jComboBoxmancc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxmancc.setPreferredSize(new java.awt.Dimension(64, 27));
        jComboBoxmancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmanccActionPerformed(evt);
            }
        });

        jComboBoxmnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxmnv.setPreferredSize(new java.awt.Dimension(64, 27));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMAPNH, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxmnv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxmancc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMAPNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldngaynhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtondoc.setText("Đọc");
        jButtondoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondocActionPerformed(evt);
            }
        });

        jButtonsua.setText("Sửa");
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });

        jButtonxoa.setText("Xóa");
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });

        jButtonthoat.setText("Thoát");
        jButtonthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthoatActionPerformed(evt);
            }
        });

        jButtonthem.setText("Thêm");
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Chức năng");

        jButtontim.setText("Tìm chính xác theo mã nhà cc");
        jButtontim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jButtonthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtontim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jButtonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jButtondoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonsua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthem)
                    .addComponent(jButtondoc)
                    .addComponent(jButtonsua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtontim)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthoat)
                    .addComponent(jButtonxoa))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablephieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã PNH", "Mã NCC", "Mã NV", "Ngày nhập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablephieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablephieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablephieunhap);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jTablechitiet_pn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã PNH", "Mã SP", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablechitiet_pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablechitiet_pnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablechitiet_pn);

        jButtonthemchitiet.setText("Thêm chi tiết");
        jButtonthemchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemchitietActionPerformed(evt);
            }
        });

        jButtonxoachitiet.setText("Xóa chi tiết");
        jButtonxoachitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoachitietActionPerformed(evt);
            }
        });

        jButtonsuachitiet.setText("Sửa chi tiết");
        jButtonsuachitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuachitietActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã PNH");

        jLabel8.setText("Mã SP");

        jTextFieldmapnh_ctpn.setEditable(false);

        jLabel9.setText("Thành Tiền");

        jTextFielddongia.setText("1");

        jLabel10.setText("Số Lượng");
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 16));

        jTextFieldsoluong.setText("1");

        jLabel11.setText("Đơn giá");

        jTextFieldthanhtien.setEditable(false);
        jTextFieldthanhtien.setText("1");
        jTextFieldthanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldthanhtienActionPerformed(evt);
            }
        });

        jComboBoxmsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButtonthemchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonxoachitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonsuachitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxmsp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldmapnh_ctpn, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielddongia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(205, 205, 205))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonthemchitiet)
                    .addComponent(jButtonxoachitiet)
                    .addComponent(jButtonsuachitiet))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldmapnh_ctpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFielddongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxmsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtondocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondocActionPerformed
        // TODO add your handling code here:
        loadpn();
      
    }//GEN-LAST:event_jButtondocActionPerformed

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        // TODO add your handling code here:
        try {
            PHIEUNHAPHANGDTO dto=new PHIEUNHAPHANGDTO();
            dto.setMAPNH(jTextFieldMAPNH.getText());
            dto.setMANCC(jComboBoxmancc.getSelectedItem().toString());
            dto.setMANV(jComboBoxmnv.getSelectedItem().toString());
            dto.setNGAYNHAP(jTextFieldngaynhap.getText());
            dto.setTONGTIEN(jTextFieldtongtien.getText());
            PHIEUNHAPHANGBUS bus= new PHIEUNHAPHANGBUS();
            if(bus.sua(dto)==true)
                loadpn();
        } catch (Exception ex) {
            Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed

        try {
            PHIEUNHAPHANGDTO dto=new PHIEUNHAPHANGDTO();
            dto.setMAPNH(jTextFieldMAPNH.getText());
            dto.setMANCC(jComboBoxmancc.getSelectedItem().toString());
            dto.setMANV(jComboBoxmnv.getSelectedItem().toString());
            dto.setNGAYNHAP(jTextFieldngaynhap.getText());
            dto.setTONGTIEN(jTextFieldtongtien.getText());
            PHIEUNHAPHANGBUS bus= new PHIEUNHAPHANGBUS();
            if(bus.them(dto)==true)
                loadpn();
        } catch (Exception ex) {
            Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonthoatActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
        if(xoa!=0)
            return;
        int i=jTablephieunhap.getSelectedRow();
     
      
            try {
                PHIEUNHAPHANGDTO dto=new PHIEUNHAPHANGDTO();
                
                dto.setMAPNH(jTextFieldMAPNH.getText());
                dto.setMANCC(jComboBoxmancc.getSelectedItem().toString());
                dto.setMANV(jComboBoxmnv.getSelectedItem().toString());
                dto.setNGAYNHAP(jTextFieldngaynhap.getText());
                PHIEUNHAPHANGBUS bus=new PHIEUNHAPHANGBUS();
                if(bus.Xoa(dto)==false)
                    return;
                int ii=0;
                for(PHIEUNHAPHANGDTO dto1: PHIEUNHAPHANGBUS.dspnh){
                    if(dto1.getMAPNH().equals(dto.getMAPNH()))
                        break;
                    else ++ii;
                }
                bus.xoavitrids(ii);
                loadpn();
            } catch (Exception ex) {
                Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jComboBoxmanccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmanccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmanccActionPerformed

    private void jTextFieldthanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldthanhtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldthanhtienActionPerformed

    private void jButtonxoachitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoachitietActionPerformed
        // TODO add your handling code here:
        int i=jTablechitiet_pn.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn chi tiết cần xóa");
            return;
        }
        else{
            if(jTextFieldmapnh_ctpn.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn cần thêm tại bảng bên");
                    return;
                }
            int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
            if(xoa!=0)
                return;


            try {
                CHITIETPHIEUNHAPHANGDTO cthddto=new CHITIETPHIEUNHAPHANGDTO();
                cthddto.setMASP(jComboBoxmsp.getSelectedItem().toString());
                if(jComboBoxmsp.getSelectedItem().toString().equals("Chọn mã SP")){
                    JOptionPane.showMessageDialog(null,"Vui lòng chọn Mã sp");
                    return;
                }
                cthddto.setMAPNH(jTextFieldMAPNH.getText());
                cthddto.setSOLUONG(jTablechitiet_pn.getValueAt(i, 3).toString());
                CHITIETPHIEUNHAPHANGBUS bus=new CHITIETPHIEUNHAPHANGBUS();
                if(bus.Xoa(cthddto)==true){
                    for(int j=0;j<bus.dscthd.size();++j){
                        if(bus.dscthd.get(j).getMAPNH().equals(cthddto.getMAPNH()) && bus.dscthd.get(j).getMASP().equals(cthddto.getMASP()))
                            bus.xoavitrids(j);
                        }
                    loadctpn();
                    loadpn();
                    
                    capnhattrusp(cthddto.getSOLUONG());

                }else{
                    JOptionPane.showMessageDialog(null,"Xóa thất bại !!");
                }
            } catch (Exception ex) {
                Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonxoachitietActionPerformed

    private void jButtonthemchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemchitietActionPerformed
        if(jTextFieldmapnh_ctpn.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn cần thêm tại bảng bên");
            return;
        }
        try{
            CHITIETPHIEUNHAPHANGBUS bus=new CHITIETPHIEUNHAPHANGBUS();
            CHITIETPHIEUNHAPHANGDTO dto=new CHITIETPHIEUNHAPHANGDTO();
            dto.setMAPNH(jTextFieldmapnh_ctpn.getText());
            dto.setMASP(jComboBoxmsp.getSelectedItem().toString());
            dto.setDONGIA(jTextFielddongia.getText());
            dto.setSOLUONG(jTextFieldsoluong.getText());
            dto.setTHANHTIEN(jTextFieldthanhtien.getText());
            
            if(bus.them(dto)==true){
                loadpn();
                loadctpn();
                capnhatsoluongsp();
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonthemchitietActionPerformed

    private void jTablephieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablephieunhapMouseClicked
        // TODO add your handling code here:
        
        int i=jTablephieunhap.getSelectedRow();
        if(i>=0){
            
            jTextFieldMAPNH.setText(jTablephieunhap.getValueAt(i, 0).toString());
            jComboBoxmancc.setSelectedItem(jTablephieunhap.getValueAt(i, 1).toString());
            jComboBoxmnv.setSelectedItem(jTablephieunhap.getValueAt(i, 2).toString());
            jTextFieldngaynhap.setText(jTablephieunhap.getValueAt(i, 3).toString());
            try{
                jTextFieldtongtien.setText(jTablephieunhap.getValueAt(i, 4).toString());
            }
            catch( Exception e){
                jTextFieldtongtien.setText("");
            }
            jTextFieldmapnh_ctpn.setText(jTextFieldMAPNH.getText());
            
            loadctpn();
            
        }
    }//GEN-LAST:event_jTablephieunhapMouseClicked

    private void jButtonsuachitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuachitietActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            
            if(jTextFieldMAPNH.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Vui lòng chọn hóa đơn cần thêm tại bảng bên");
                return;
            }
            
            CHITIETPHIEUNHAPHANGBUS bus=new CHITIETPHIEUNHAPHANGBUS();
            CHITIETPHIEUNHAPHANGDTO dto=new CHITIETPHIEUNHAPHANGDTO();
            dto.setMAPNH(jTextFieldmapnh_ctpn.getText());
            dto.setMASP(jComboBoxmsp.getSelectedItem().toString());
            dto.setDONGIA(jTextFielddongia.getText());
            dto.setSOLUONG(jTextFieldsoluong.getText());    
            dto.setTHANHTIEN(jTextFieldthanhtien.getText());
            
            String slcu=bus.timtheoma(dto);
            
            if(bus.sua(dto)==true){
                loadpn();
                loadctpn();
                capnhatsuasp(slcu,dto.getSOLUONG());
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(Hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonsuachitietActionPerformed

    private void jTablechitiet_pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablechitiet_pnMouseClicked
        // TODO add your handling code here:
        int i=jTablechitiet_pn.getSelectedRow();
        if(i>=0){
            if(jTextFieldmapnh_ctpn.getText().equals(""))
                return;
            jTextFielddongia.setText(jTablechitiet_pn.getValueAt(i,2).toString());
            jTextFieldsoluong.setText(jTablechitiet_pn.getValueAt(i,3).toString());
            jTextFieldthanhtien.setText(jTablechitiet_pn.getValueAt(i,4).toString());
            jComboBoxmsp.setSelectedItem(jTablechitiet_pn.getValueAt(i,1));
        }
    }//GEN-LAST:event_jTablechitiet_pnMouseClicked

    private void jButtontimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimActionPerformed
        // TODO add your handling code here:
        String mcc=JOptionPane.showInputDialog(null,"Mời nhập mã nhà cung cấp");
        PHIEUNHAPHANGBUS bus=new PHIEUNHAPHANGBUS();
        PHIEUNHAPHANGDTO dto= new PHIEUNHAPHANGDTO();
        dto=bus.tim(mcc);
        if(dto==null)
            return;
        else{
            jTextFieldMAPNH.setText(dto.getMAPNH());
            jTextFieldngaynhap.setText(dto.getNGAYNHAP());
            jTextFieldtongtien.setText(dto.getTONGTIEN());
            jComboBoxmnv.setSelectedItem(dto.getMANV());
            jComboBoxmancc.setSelectedItem(dto.getMANCC());
        }
    }//GEN-LAST:event_jButtontimActionPerformed
    public void loadcbncc(){
        DefaultComboBoxModel mocb=new DefaultComboBoxModel();
        NCCBUS bus=new NCCBUS();
        bus.doc();
        for(NCCDTO dto: NCCBUS.dsnccbus){
            mocb.addElement(dto.getMANCC());
        }
        jComboBoxmancc.setModel(mocb);
    }
    public void loadcbnv(){
        DefaultComboBoxModel mocb=new DefaultComboBoxModel();
        NHANVIENBUS bus=new NHANVIENBUS();
        bus.hienthi();
        for(NHANVIENDTO dto: NHANVIENBUS.dsnv){
            mocb.addElement(dto.getMANV());
        }
        jComboBoxmnv.setModel(mocb);
    }
    public void loadpn(){
        PHIEUNHAPHANGBUS  bus =new PHIEUNHAPHANGBUS();
        bus.doc();
        Vector he=new Vector();
        he.add("Mã PNH");
        he.add("Mã NCC");
        he.add("Mã NV");
        he.add("NGày Nhập");
        he.add("Tổng tiền");
        DefaultTableModel model=new DefaultTableModel(he,0);
        for(PHIEUNHAPHANGDTO dto: PHIEUNHAPHANGBUS.dspnh){
            Vector r=new Vector();
            r.add(dto.getMAPNH());
            r.add(dto.getMANCC());
            r.add(dto.getMANV());
            r.add(dto.getNGAYNHAP());
            r.add(dto.getTONGTIEN());
            model.addRow(r);
            bus.sua2(dto);
        }
        jTablephieunhap.setModel(model);
    }
    public void loadmasp(){
        DefaultComboBoxModel mdsp=new DefaultComboBoxModel();
        mdsp.addElement("Chọn Mã SP");
        SANPHAMBUS bus=new SANPHAMBUS();
        bus.DocSanPham();
        for(SANPHAMDTO sp: SANPHAMBUS.lssanpham)
            mdsp.addElement(sp.getMASP());
        jComboBoxmsp.setModel(mdsp);
    }
    public void loadctpn(){
        CHITIETPHIEUNHAPHANGBUS  bus =new CHITIETPHIEUNHAPHANGBUS();
        bus.doc();
        Vector he=new Vector();
        he.add("Mã PNH");
        he.add("Mã SP");
        he.add("Đơn giá");
        he.add("Số lượng");
        he.add("Thành tiền");
        DefaultTableModel model=new DefaultTableModel(he,0);
        for(CHITIETPHIEUNHAPHANGDTO dto: CHITIETPHIEUNHAPHANGBUS.dscthd){
            if(!dto.getMAPNH().equals(jTextFieldmapnh_ctpn.getText()))
                continue;
            Vector r=new Vector();
            r.add(dto.getMAPNH());
            r.add(dto.getMASP());
            r.add(dto.getDONGIA());
            r.add(dto.getSOLUONG());
            r.add(dto.getTHANHTIEN());
            model.addRow(r);
        }
        jTablechitiet_pn.setModel(model);
    }
    public void capnhatsoluongsp(){
        try {
            SANPHAMDTO a=new SANPHAMDTO();
            SANPHAMBUS bus=new SANPHAMBUS();
            a=bus.timtheoma(jComboBoxmsp.getSelectedItem().toString());
            a.setSOLUONG(String.valueOf(Integer.parseInt(a.getSOLUONG())+Integer.parseInt(jTextFieldsoluong.getText())));

            bus.SuaSanPham2(a);
        } catch (SQLException ex) {
            Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void capnhattrusp(String a1){
        try {
            SANPHAMDTO a=new SANPHAMDTO();
            SANPHAMBUS bus=new SANPHAMBUS();
            a=bus.timtheoma(jComboBoxmsp.getSelectedItem().toString());
            a.setSOLUONG(String.valueOf(Integer.parseInt(a.getSOLUONG())-Integer.parseInt(a1)));
            bus.SuaSanPham2(a);
        } catch (SQLException ex) {
            Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void capnhatsuasp(String a1,String a2){
        try {
            SANPHAMDTO a=new SANPHAMDTO();
            SANPHAMBUS bus=new SANPHAMBUS();
            a=bus.timtheoma(jComboBoxmsp.getSelectedItem().toString());
            a.setSOLUONG(String.valueOf(Integer.parseInt(a.getSOLUONG())+Integer.parseInt(a2)-Integer.parseInt(a1)));
            bus.SuaSanPham2(a);
        } catch (SQLException ex) {
            Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PHIEUNHAPHANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PHIEUNHAPHANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondoc;
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonsuachitiet;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtonthemchitiet;
    private javax.swing.JButton jButtonthoat;
    private javax.swing.JButton jButtontim;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JButton jButtonxoachitiet;
    private javax.swing.JComboBox<String> jComboBoxmancc;
    private javax.swing.JComboBox<String> jComboBoxmnv;
    private javax.swing.JComboBox<String> jComboBoxmsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablechitiet_pn;
    private javax.swing.JTable jTablephieunhap;
    private javax.swing.JTextField jTextFieldMAPNH;
    private javax.swing.JTextField jTextFielddongia;
    private javax.swing.JTextField jTextFieldmapnh_ctpn;
    private javax.swing.JTextField jTextFieldngaynhap;
    private javax.swing.JTextField jTextFieldsoluong;
    private javax.swing.JTextField jTextFieldthanhtien;
    private javax.swing.JTextField jTextFieldtongtien;
    // End of variables declaration//GEN-END:variables
}
