/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LoaiSanPhamBUS;
import BUS.SANPHAMBUS;
import DTO.LoaiSanPhamDTO;
import DTO.SANPHAMDTO;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Asus
 */
public class Sanpham extends javax.swing.JFrame {

    /**
     * Creates new form Sanpham
     */
    public Sanpham() {
        initComponents();
        SANPHAMBUS bus=new SANPHAMBUS();
        if(SANPHAMBUS.lssanpham==null)
            bus.DocSanPham();
        
        Vector he=new Vector();
        he.add("Mã SP");
        he.add("Tên SP");
        he.add("Ngày SX");
        he.add("Số lượng");
        he.add("Đơn giá");
        he.add("Mã loại");
        
        DefaultTableModel model = new DefaultTableModel(he,0);
        
        for(SANPHAMDTO SP:SANPHAMBUS.lssanpham){
            Vector r=new Vector();
            r.add(SP.getMASP());
            r.add(SP.getTENSP());
            r.add(SP.getNGAYSX());
            r.add(SP.getSOLUONG());
            r.add(SP.getDONGIA());
            r.add(SP.getMALOAI());
            
            model.addRow(r);
        }
        jTable1.setModel(model);
        
        LoaiSanPhamBUS lspbus=new LoaiSanPhamBUS();
        lspbus.DocLoaiSanPham();
        DefaultComboBoxModel cbmd=new DefaultComboBoxModel();
        for(LoaiSanPhamDTO ldto: LoaiSanPhamBUS.loaisanpham){
            cbmd.addElement(ldto.getMaloai());
        }
        jComboBoxmaloai.setModel(cbmd);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldmasanpham = new javax.swing.JTextField();
        jTextFieldtensanpham = new javax.swing.JTextField();
        jTextFieldngaysanxuat = new javax.swing.JTextField();
        jTextFieldsoluong = new javax.swing.JTextField();
        jTextFielddongia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxmaloai = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButtonthem = new javax.swing.JButton();
        jButtonxoa = new javax.swing.JButton();
        jButtonsua = new javax.swing.JButton();
        jButtontimtheoma = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jButtonhienthi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtontimnangcao = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldgiamin = new javax.swing.JTextField();
        jTextFieldgiamax = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldtungay = new javax.swing.JTextField();
        jTextFielddenngay = new javax.swing.JTextField();
        jTextFieldten = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonThongke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã sản phẩm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ngày sản xuất");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đơn giá");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã loại");

        jTextFieldmasanpham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldtensanpham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextFieldngaysanxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldngaysanxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldngaysanxuatActionPerformed(evt);
            }
        });

        jTextFieldsoluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsoluongActionPerformed(evt);
            }
        });

        jTextFielddongia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFielddongia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddongiaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THÔNG TIN SẢN PHẨM");

        jComboBoxmaloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFielddongia, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldngaysanxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldtensanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jTextFieldmasanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jComboBoxmaloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmasanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldtensanpham)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldngaysanxuat)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFielddongia, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmaloai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jButtonthem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonthem.setText("Thêm");
        jButtonthem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonthemActionPerformed(evt);
            }
        });

        jButtonxoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonxoa.setText("Xóa");
        jButtonxoa.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxoaActionPerformed(evt);
            }
        });

        jButtonsua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonsua.setText("Sửa");
        jButtonsua.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsuaActionPerformed(evt);
            }
        });

        jButtontimtheoma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtontimtheoma.setText("Tìm kiếm theo mã");
        jButtontimtheoma.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtontimtheoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimtheomaActionPerformed(evt);
            }
        });

        jButtonThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jButtonhienthi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonhienthi.setText("Hiển thị");
        jButtonhienthi.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhienthiActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TÌM KIẾM NÂNG CAO");

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 51, 0)));

        jButtontimnangcao.setText("tìm");
        jButtontimnangcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimnangcaoActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Giá MAX");

        jLabel12.setText("Giá Min");

        jLabel14.setText("Khoảng giá");

        jTextFieldgiamin.setText("0");

        jTextFieldgiamax.setText("2000000000");
        jTextFieldgiamax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgiamaxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgiamax, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jTextFieldgiamin))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldgiamin, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldgiamax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Khoảng thời gian sản xuất");

        jLabel16.setText("Từ ngày");

        jLabel17.setText("Đến ngày");

        jTextFieldtungay.setText("1980-12-31");
        jTextFieldtungay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtungayActionPerformed(evt);
            }
        });

        jTextFielddenngay.setText("9999-12-31");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFielddenngay, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldtungay))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldtungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielddenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldten.setPreferredSize(new java.awt.Dimension(6, 23));
        jTextFieldten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtenActionPerformed(evt);
            }
        });

        jLabel11.setText("Tên");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldten, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtontimnangcao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldten, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButtontimnangcao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHỨC NĂNG");

        jButtonThongke.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonThongke.setText("Thống kê");
        jButtonThongke.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 3, 2, 3, new java.awt.Color(255, 255, 102)));
        jButtonThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonhienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonsua, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtontimtheoma, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(jButtonThongke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonthem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonxoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonhienthi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtontimtheoma))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Ngày sản xuất", "Số lượng", "Đơn giá", "Mã loại", "Hình ảnh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsoluongActionPerformed

    private void jButtonhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhienthiActionPerformed
        // TODO add your handling code here:
        SANPHAMBUS bus=new SANPHAMBUS();
        if(SANPHAMBUS.lssanpham==null)
            bus.DocSanPham();
        
        Vector he=new Vector();
        he.add("Mã SP");
        he.add("Tên SP");
        he.add("Ngày SX");
        he.add("Số lượng");
        he.add("Đơn giá");
        he.add("Mã loại");
        dangthongke=0;
        DefaultTableModel model = new DefaultTableModel(he,0);
        
        for(SANPHAMDTO SP:SANPHAMBUS.lssanpham){
            Vector r=new Vector();
            r.add(SP.getMASP());
            r.add(SP.getTENSP());
            r.add(SP.getNGAYSX());
            r.add(SP.getSOLUONG());
            r.add(SP.getDONGIA());
            r.add(SP.getMALOAI());
            
            model.addRow(r);
        }
        jTable1.setModel(model);

    }//GEN-LAST:event_jButtonhienthiActionPerformed

    private void jButtonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonthemActionPerformed
        // TODO add your handling code here:
         SANPHAMDTO a=new SANPHAMDTO();
                    a.setMASP(jTextFieldmasanpham.getText());
                    a.setTENSP(jTextFieldtensanpham.getText());
                    a.setNGAYSX(jTextFieldngaysanxuat.getText());
                    a.setSOLUONG(jTextFieldsoluong.getText());
                    a.setDONGIA(jTextFielddongia.getText());
                    a.setMALOAI(jComboBoxmaloai.getSelectedItem().toString());
        SANPHAMBUS bus=new SANPHAMBUS();
        try {
            if(bus.ThemSanPham(a)==true){
                if(SANPHAMBUS.lssanpham==null)
                    bus.DocSanPham();

                Vector he=new Vector();
                he.add("Mã SP");
                he.add("Tên SP");
                he.add("Ngày SX");
                he.add("Số lượng");
                he.add("Đơn giá");
                he.add("Mã loại");
                dangthongke=0;
                model=new DefaultTableModel(he,0);

                 for(SANPHAMDTO SP:SANPHAMBUS.lssanpham){
                    Vector r=new Vector();
                    r.add(SP.getMASP());
                    r.add(SP.getTENSP());
                    r.add(SP.getNGAYSX());
                    r.add(SP.getSOLUONG());
                    r.add(SP.getDONGIA());
                    r.add(SP.getMALOAI());
                    
                    model.addRow(r);
                }
                jTable1.setModel(model);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonthemActionPerformed

    private void jButtonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxoaActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        int xoa=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa ?");
        if(xoa!=0)
            return;
        int i=jTable1.getSelectedRow();
        if(i>=0 ){           
            {
                try {
                    SANPHAMBUS bus=new SANPHAMBUS();
                    if(SANPHAMBUS.lssanpham==null)
                        bus.DocSanPham();
                    
                    SANPHAMDTO a=new SANPHAMDTO();
                    a.setMASP(jTextFieldmasanpham.getText());
                    a.setTENSP(jTextFieldtensanpham.getText());
                    a.setNGAYSX(jTextFieldngaysanxuat.getText());
                    a.setSOLUONG(jTextFieldsoluong.getText());
                    a.setDONGIA(jTextFielddongia.getText());
                    a.setMALOAI(jComboBoxmaloai.getSelectedItem().toString());
                    if(bus.XoaSanPham(a)==false)
                        return;
                    bus.xoavitrids(i);
                    
                    //model.removeRow(i);
                    //jTable1.setModel(model);
        
                    Vector he=new Vector();
                    he.add("Mã SP");
                    he.add("Tên SP");
                    he.add("Ngày SX");
                    he.add("Số lượng");
                    he.add("Đơn giá");
                    he.add("Mã loại");
                    dangthongke=0;
                    DefaultTableModel model = new DefaultTableModel(he,0);

                    for(SANPHAMDTO SP:SANPHAMBUS.lssanpham){
                        Vector r=new Vector();
                        r.add(SP.getMASP());
                        r.add(SP.getTENSP());
                        r.add(SP.getNGAYSX());
                        r.add(SP.getSOLUONG());
                        r.add(SP.getDONGIA());
                        r.add(SP.getMALOAI());
                        
                        model.addRow(r);
                    }
                    jTable1.setModel(model);

                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButtonxoaActionPerformed

    private void jButtonsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsuaActionPerformed
        // TODO add your handling code here:
        SANPHAMDTO a=new SANPHAMDTO();
                    a.setMASP(jTextFieldmasanpham.getText());
                    a.setTENSP(jTextFieldtensanpham.getText());
                    a.setNGAYSX(jTextFieldngaysanxuat.getText());
                    a.setSOLUONG(jTextFieldsoluong.getText());
                    a.setDONGIA(jTextFielddongia.getText());
                    a.setMALOAI(jComboBoxmaloai.getSelectedItem().toString());
        
        SANPHAMBUS bus=new SANPHAMBUS();
        try {
            bus.SuaSanPham(a);
        } catch (SQLException ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(SANPHAMBUS.lssanpham==null)
            bus.DocSanPham();
        
        Vector he=new Vector();
        he.add("Mã SP");
        he.add("Tên SP");
        he.add("Ngày SX");
        he.add("Số lượng");
        he.add("Đơn giá");
        he.add("Mã loại");
        dangthongke=0;
        model=new DefaultTableModel(he,0);
        
      for(SANPHAMDTO SP:SANPHAMBUS.lssanpham){
            Vector r=new Vector();
            r.add(SP.getMASP());
            r.add(SP.getTENSP());
            r.add(SP.getNGAYSX());
            r.add(SP.getSOLUONG());
            r.add(SP.getDONGIA());
            r.add(SP.getMALOAI());
            
            model.addRow(r);
        }
        jTable1.setModel(model);

    }//GEN-LAST:event_jButtonsuaActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        // TODO add your handling code here:
            this.dispose();
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         // TODO add your handling code here:
         if(dangthongke==1)
             return;
         int i=jTable1.getSelectedRow();
         if(i>=0){
             jTextFieldmasanpham.setText(jTable1.getValueAt(i,0).toString());
             jTextFieldtensanpham.setText(jTable1.getValueAt(i,1).toString());
             jTextFieldngaysanxuat.setText(jTable1.getValueAt(i,2).toString());
             jTextFieldsoluong.setText(jTable1.getValueAt(i,3).toString());
             jTextFielddongia.setText(jTable1.getValueAt(i,4).toString());
             jComboBoxmaloai.setSelectedItem(jTable1.getValueAt(i,5).toString());
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtontimtheomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimtheomaActionPerformed
         // TODO add your handling code here:
        String se=JOptionPane.showInputDialog("Mời nhập chính xác MASP");
        SANPHAMBUS kh=new SANPHAMBUS();
        SANPHAMDTO aa=new SANPHAMDTO();
        aa=kh.timtheoma(se);
        if(aa==null)
            JOptionPane.showMessageDialog(null,"Không tìm thấy");
        else{
            jTextFieldmasanpham.setText(aa.getMASP());
            jTextFieldtensanpham.setText(aa.getTENSP());
            jTextFieldngaysanxuat.setText(aa.getNGAYSX());
            jTextFieldsoluong.setText(aa.getSOLUONG());
            jTextFielddongia.setText(aa.getDONGIA());
            jComboBoxmaloai.setSelectedItem(aa.getMALOAI());
            
        }
    }//GEN-LAST:event_jButtontimtheomaActionPerformed

    private void jTextFieldgiamaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgiamaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgiamaxActionPerformed

    private void jTextFieldtungayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtungayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtungayActionPerformed

    private void jButtontimnangcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimnangcaoActionPerformed
        try {
            dangthongke=0;
            // TODO add your handling code here:
            ArrayList<SANPHAMDTO> nangcao=new ArrayList<SANPHAMDTO>();
            SANPHAMBUS b=new SANPHAMBUS();
            String ten=jTextFieldten.getText();
            String giamin=jTextFieldgiamin.getText();
            String giamax=jTextFieldgiamax.getText();
            String ngbd=jTextFieldtungay.getText();
            String ngkt=jTextFielddenngay.getText();
            
            try{
                Integer.parseInt(giamin);
                Integer.parseInt(giamax);
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Khoảng giá không hợp lệ(vui lòng nhập số nguyên dương bé hơn hoặc bằng 2 tỷ)");
                return;
            }
            
            try{
                Date.valueOf(ngbd);
                Date.valueOf(ngkt);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Khoảng ngày sản xuất không hợp lệ");
                return;
            }
            nangcao=b.timnangcao(ten, giamin, giamax, ngbd, ngkt);
            Vector he=new Vector();
            he.add("Mã SP");
            he.add("Tên SP");
            he.add("Ngày SX");
            he.add("Số lượng");
            he.add("Đơn giá");
            he.add("Mã loại");
            
            model=new DefaultTableModel(he,0);

            for(SANPHAMDTO SP:nangcao){
                  Vector r=new Vector();
                  r.add(SP.getMASP());
                  r.add(SP.getTENSP());
                  r.add(SP.getNGAYSX());
                  r.add(SP.getSOLUONG());
                  r.add(SP.getDONGIA());
                  r.add(SP.getMALOAI());
                 
                  model.addRow(r);
              }
              jTable1.setModel(model);

        } catch (ParseException ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtontimnangcaoActionPerformed

    private void jTextFieldtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtenActionPerformed

    private void jButtonThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThongkeActionPerformed
        // TODO add your handling code here:
        dangthongke=1;
        SANPHAMBUS bus=new SANPHAMBUS();
        ArrayList<SANPHAMDTO> ar=new ArrayList<>();
        ar=bus.thongke();
        Vector he=new Vector();
        he.add("Mã loại");
        he.add("Số lượng");
        DefaultTableModel model=new DefaultTableModel(he,0);
        for(SANPHAMDTO b: ar){
            Vector r=new Vector();
            r.add(b.getMALOAI());
            r.add(b.getSOLUONG());
            model.addRow(r);
        }
        jTable1.setModel(model);
    }//GEN-LAST:event_jButtonThongkeActionPerformed

    private void jTextFieldngaysanxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldngaysanxuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldngaysanxuatActionPerformed

    private void jTextFielddongiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddongiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddongiaActionPerformed

    
    
    /**
     * 
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sanpham().setVisible(true);
            }
        });
    }
    
    private DefaultTableModel model;
    private int dangthongke=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonThongke;
    private javax.swing.JButton jButtonhienthi;
    private javax.swing.JButton jButtonsua;
    private javax.swing.JButton jButtonthem;
    private javax.swing.JButton jButtontimnangcao;
    private javax.swing.JButton jButtontimtheoma;
    private javax.swing.JButton jButtonxoa;
    private javax.swing.JComboBox<String> jComboBoxmaloai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielddenngay;
    private javax.swing.JTextField jTextFielddongia;
    private javax.swing.JTextField jTextFieldgiamax;
    private javax.swing.JTextField jTextFieldgiamin;
    private javax.swing.JTextField jTextFieldmasanpham;
    private javax.swing.JTextField jTextFieldngaysanxuat;
    private javax.swing.JTextField jTextFieldsoluong;
    private javax.swing.JTextField jTextFieldten;
    private javax.swing.JTextField jTextFieldtensanpham;
    private javax.swing.JTextField jTextFieldtungay;
    // End of variables declaration//GEN-END:variables
}
